name: CI
on: [pull_request, push]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov pint numpy scipy matplotlib
  
      - name: Run tests
        run: |
          python -m pytest test/ --cov libra_toolbox --cov-report xml --cov-report term
      
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}