name: CI
on: [pull_request, push]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
  
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov pint numpy scipy matplotlib
  
      - name: Run tests
        run: |
          python -m pytest test/ --cov libra_toolbox --cov-report xml --cov-report term
      
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}